// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsyUYzOfRI6mHjmxOKjAZdZsossVHev8o',
    appId: '1:497092127125:web:8146fd137b8c55de0d2e9c',
    messagingSenderId: '497092127125',
    projectId: 'quiz-app-282bc',
    authDomain: 'quiz-app-282bc.firebaseapp.com',
    storageBucket: 'quiz-app-282bc.appspot.com',
    measurementId: 'G-2Q2DLF19R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaohD6OFEyNKvw5MIBnYGKg4aE5ABpa3E',
    appId: '1:497092127125:android:6fcf71cdfbbd23530d2e9c',
    messagingSenderId: '497092127125',
    projectId: 'quiz-app-282bc',
    storageBucket: 'quiz-app-282bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvqmQIF4K_p9GG6QVZcr5fWh-dhZpA4Eo',
    appId: '1:497092127125:ios:35344e340913661d0d2e9c',
    messagingSenderId: '497092127125',
    projectId: 'quiz-app-282bc',
    storageBucket: 'quiz-app-282bc.appspot.com',
    iosClientId: '497092127125-5s2h1ncnveot7hv9kbcn42q898v6q9ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvqmQIF4K_p9GG6QVZcr5fWh-dhZpA4Eo',
    appId: '1:497092127125:ios:35344e340913661d0d2e9c',
    messagingSenderId: '497092127125',
    projectId: 'quiz-app-282bc',
    storageBucket: 'quiz-app-282bc.appspot.com',
    iosClientId: '497092127125-5s2h1ncnveot7hv9kbcn42q898v6q9ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
